// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

//_______________________
// BAGIAN IMPORT DEPENDENSI | BERFUNGSI SEBAGAI PUSAT UNTUK MENGIMPOR KELAS DAN MODUL KONFIGURASI PLATFORM
//_______________________

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions; // Mengimpor kelas FirebaseOptions secara spesifik yang berfungsi sebagai struktur cetak biru dokumen konfigurasi Firebase
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform; // Mengimpor properti dasar Flutter yang berfungsi melakukan pengecekan jenis platform fisik dan lingkungan web target eksekusi

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

//_______________________
// BAGIAN CLASS UTAMA OPTIONS | BERFUNGSI SEBAGAI PUSAT PENYEDIA DATA KREDENSIAL KONFIGURASI SETIAP PLATFORM
//_______________________

class DefaultFirebaseOptions {
  
  //_______________________
  // BAGIAN PENGECEKAN PLATFORM (GETTER) | BERFUNGSI MELAKUKAN PEMILIHAN OTOMATIS DATA KREDENSIAL YANG SESUAI
  //_______________________

  static FirebaseOptions get currentPlatform { // Fungsi getter statis yang berfungsi mengembalikan konfigurasi yang sesuai dengan platform yang sedang berjalan
    if (kIsWeb) { // Melakukan pengecekan apakah aplikasi sedang dijalankan di dalam lingkungan peramban web
      return web; // Mengembalikan objek konfigurasi kredensial Firebase khusus untuk platform web
    }
    switch (defaultTargetPlatform) { // Melakukan percabangan guna mendeteksi jenis sistem operasi perangkat keras yang dituju
      case TargetPlatform.android: // Kondisi jika aplikasi terdeteksi berjalan pada ekosistem sistem operasi Android
        return android; // Mengembalikan objek konfigurasi kredensial Firebase khusus untuk platform Android
      case TargetPlatform.iOS: // Kondisi untuk sistem operasi iOS
        throw UnsupportedError( // Melempar pesan kesalahan enkapsulasi jika sistem mendeteksi platform ini belum dikonfigurasi oleh CLI
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS: // Kondisi untuk sistem operasi macOS
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows: // Kondisi untuk sistem operasi Windows
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux: // Kondisi untuk sistem operasi Linux
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default: // Kondisi standar jika platform tidak dikenali oleh sistem pengondisian
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //_______________________
  // BAGIAN DATA KREDENSIAL ANDROID | BERFUNGSI MENYIMPAN ATRIBUT IDENTITAS PROYEK FIREBASE ANDROID
  //_______________________

  static const FirebaseOptions android = FirebaseOptions( // Mendeklarasikan konstanta objek konfigurasi Firebase khusus untuk aplikasi versi Android
    apiKey: 'AIzaSyDsMg6CUe__fgvOrmDShW-mCEX7hzXDgZA', // Menyimpan kunci API unik dari konsol Firebase yang berfungsi membuka akses otentikasi
    appId: '1:222368323205:android:b703745499633205de3bec', // Menyimpan ID unik aplikasi Android yang terdaftar di server database Firebase
    messagingSenderId: '222368323205', // Menyimpan ID pengirim yang berfungsi sebagai parameter identitas pengiriman pesan push notification
    projectId: 'contacta-app-8fecb', // Menyimpan nama ID unik dari proyek cloud utama yang mewadahi aplikasi ini
    storageBucket: 'contacta-app-8fecb.firebasestorage.app', // Menyimpan alamat direktori penyimpanan awan yang berfungsi mengelola berkas atau file pengguna
  );

  //_______________________
  // BAGIAN DATA KREDENSIAL WEB | BERFUNGSI MENYIMPAN ATRIBUT IDENTITAS PROYEK FIREBASE WEB
  //_______________________

  static const FirebaseOptions web = FirebaseOptions( // Mendeklarasikan konstanta objek konfigurasi Firebase khusus untuk aplikasi versi Web
    apiKey: 'AIzaSyDNLrWEaI1eViyARCskwzL7M2FFKhN8KYs', // Menyimpan kunci API khusus peramban yang berfungsi menghubungkan modul enkripsi web
    appId: '1:222368323205:web:7f82d1f43f9fa0dbde3bec', // Menyimpan ID unik web aplikasi untuk registrasi parameter di server Firebase
    messagingSenderId: '222368323205', // Menyimpan konfigurasi ID pengirim pesan untuk ekosistem web browser
    projectId: 'contacta-app-8fecb', // Menyimpan pengenal identitas proyek inti yang terhubung secara terpusat
    authDomain: 'contacta-app-8fecb.firebaseapp.com', // Menyimpan domain otentikasi resmi yang berfungsi menangani sistem login pihak ketiga pada web
    storageBucket: 'contacta-app-8fecb.firebasestorage.app', // Menyimpan rujukan wadah penyimpanan berkas digital versi web
    measurementId: 'G-N4124L1NHQ', // Menyimpan token analitik yang berfungsi melacak aktivitas performa aplikasi pada lingkungan web
  );

}